### PR TITLE
Added another config file format

### PR DESCRIPTION
**Pull request by evokerking1**
Added the .properties file format

### CODE REVIEW

**Comment by evokerking1** [comment]
since thats Minecraft's server software config file

**Comment by evokerking1** [comment]
@privt00 Can you merge since i have another config file format

**Comment by privt00** [comment]
pleas make everything in one pull request

**Comment by evokerking1** [comment]
> pleas make everything in one pull request

what do you mean?

**Comment by privt00** [comment]
you said you have also a other pr to do

**Comment by evokerking1** [comment]
> you said you have also a other pr to do

what's the other one? Can you remind me?

**Comment by privt00** [comment]
i have no clue read the context of this pr

**Pull request merged**
